{"id": "CWE-1088", "description": "The code has a synchronous call to a remote resource, but there is no timeout for the call, or the timeout is set to infinite.", "hackerone": {"collected_date": "2024-08-26T03:30:06Z", "total_reports": 83, "unique_reports_last_12_weeks": 8, "severity_distribution": {"all_time": {"critical": 0, "high": 0, "medium": 0, "low": 0}}, "change_distribution": {"days_past": 0, "critical": 0, "high": 0, "medium": 0, "low": 0}}, "bugcrowd": {"collected_date": "2024-08-26T03:30:06Z", "vrt_id": "unavailable", "parent_vrt_id": "unavailable", "vrt_priority": 0}}