{"id": "CWE-1088", "description": "The code has a synchronous call to a remote resource, but there is no timeout for the call, or the timeout is set to infinite.", "hackerone": {"collected_date": "2024-09-11T03:16:18Z", "total_reports": 84, "unique_reports_last_12_weeks": 2, "severity_distribution": {"all_time": {"critical": 0, "high": 0, "medium": 0, "low": 0}}, "change_distribution": {"days_past": 6, "critical": 0, "high": 0, "medium": 0, "low": 0}}, "bugcrowd": {"collected_date": "2024-09-11T03:16:18Z", "vrt_id": [], "parent_vrt_id": [], "vrt_priority": 0}}